# Generated by Django 5.2.4 on 2026-08-03 13:26

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('campaigns', '0001_initial'),
        ('telephony', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NpaJurisdiction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('npa', models.CharField(max_length=3, unique=True)),
                ('state', models.CharField(max_length=2)),
                ('timezone', models.CharField(blank=True, max_length=48)),
            ],
            options={
                'indexes': [models.Index(fields=['npa'], name='compliance__npa_96e7c0_idx')],
            },
        ),
        migrations.CreateModel(
            name='CallingWindow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jurisdiction', models.CharField(max_length=8)),
                ('start_local', models.TimeField()),
                ('end_local', models.TimeField()),
                ('weekdays', models.JSONField(default=list)),
                ('holidays_blocked', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'jurisdiction'], name='compliance__organiz_f49e97_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'jurisdiction'), name='uniq_window_per_jurisdiction')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unfiltered', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('out_of_window_dial', 'Call placed outside window'), ('suppressed_dial', 'Call placed to suppressed number'), ('missing_consent', 'Call placed without consent record'), ('rate_breach', 'Configured pacing limit exceeded'), ('complaint', 'Consumer complaint')], max_length=32)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='telephony.calllog')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='campaigns.campaign')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'kind', '-created_at'], name='compliance__organiz_1ac797_idx'), models.Index(condition=models.Q(('acknowledged_at__isnull', True)), fields=['organization', '-created_at'], name='idx_incident_open')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unfiltered', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DNCEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_e164', models.CharField(blank=True, max_length=16)),
                ('phone_hash', models.CharField(max_length=64)),
                ('reason', models.CharField(choices=[('internal_dnc', 'Internal DNC'), ('ivr_opt_out', 'Opted out via IVR'), ('federal_dnc', 'Federal DNC registry'), ('state_dnc', 'State DNC registry'), ('litigator', 'Known litigator / trap line'), ('carrier_invalid', 'Invalid or unassigned number'), ('wireless_block', 'Wireless, no consent on file'), ('complaint', 'Complaint received'), ('erasure_request', 'GDPR/CCPA erasure request'), ('no_consent', 'No consent record on file'), ('out_of_window', 'Outside permitted calling window'), ('attempt_cap', 'Daily attempt cap reached')], max_length=24)),
                ('notes', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_global', models.BooleanField(default=False, help_text='Platform-wide suppression, visible to every tenant.')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
                ('scope_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dnc_entries', to='campaigns.campaign')),
                ('source_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='telephony.calllog')),
            ],
            options={
                'verbose_name': 'DNC entry',
                'verbose_name_plural': 'DNC entries',
                'indexes': [models.Index(fields=['organization', 'phone_hash'], name='compliance__organiz_6ecf3e_idx'), models.Index(condition=models.Q(('is_global', True)), fields=['phone_hash'], name='idx_dnc_global'), models.Index(fields=['organization', '-created_at'], name='compliance__organiz_0bc703_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('scope_campaign__isnull', False)), fields=('organization', 'phone_hash', 'scope_campaign'), name='uniq_dnc_scoped'), models.UniqueConstraint(condition=models.Q(('scope_campaign__isnull', True)), fields=('organization', 'phone_hash'), name='uniq_dnc_org_wide')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unfiltered', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ScrubJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('federal_dnc', 'Federal DNC registry'), ('state_dnc', 'State DNC registry'), ('litigator', 'Litigator / trap line vendor'), ('manual', 'Manual upload')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('records_processed', models.PositiveIntegerField(default=0)),
                ('records_added', models.PositiveIntegerField(default=0)),
                ('contacts_suppressed', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'source', '-created_at'], name='compliance__organiz_246e75_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unfiltered', django.db.models.manager.Manager()),
            ],
        ),
    ]
