# Generated by Django 5.2.4 on 2026-08-03 13:26

import datetime
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('contacts', '0001_initial'),
        ('ivr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallerID',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_e164', models.CharField(max_length=16, unique=True)),
                ('friendly_name', models.CharField(blank=True, max_length=80)),
                ('provider', models.CharField(max_length=16)),
                ('provider_sid', models.CharField(blank=True, max_length=64)),
                ('attestation', models.CharField(default='C', max_length=1)),
                ('trust_product_sid', models.CharField(blank=True, max_length=64)),
                ('cnam_display', models.CharField(blank=True, max_length=15)),
                ('branded_calling_enrolled', models.BooleanField(default=False)),
                ('reputation_score', models.FloatField(blank=True, null=True)),
                ('reputation_checked_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('daily_call_cap', models.PositiveIntegerField(default=0)),
                ('calls_today', models.PositiveIntegerField(default=0)),
                ('calls_today_date', models.DateField(blank=True, null=True)),
                ('rested_until', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unfiltered', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('running', 'Running'), ('paused', 'Paused'), ('throttled', 'Throttled by carrier'), ('completed', 'Completed'), ('stopped', 'Stopped'), ('failed', 'Failed')], db_index=True, default='draft', max_length=16)),
                ('provider', models.CharField(blank=True, max_length=16)),
                ('requires_consent', models.BooleanField(default=True)),
                ('consent_scope', models.CharField(choices=[('marketing', 'Marketing'), ('informational', 'Informational')], default='marketing', max_length=32)),
                ('cps_limit', models.FloatField(default=1.0, help_text='Calls placed per second, enforced globally via Redis token bucket.', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(100)])),
                ('max_concurrent_channels', models.PositiveIntegerField(default=30, help_text='Ceiling on simultaneously live calls.')),
                ('ring_timeout_seconds', models.PositiveSmallIntegerField(default=30)),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('scheduled_end', models.DateTimeField(blank=True, null=True)),
                ('window_start_local', models.TimeField(default=datetime.time(9, 0))),
                ('window_end_local', models.TimeField(default=datetime.time(17, 0))),
                ('active_weekdays', models.JSONField(default=list)),
                ('respect_contact_timezone', models.BooleanField(default=True)),
                ('fallback_timezone', models.CharField(default='UTC', max_length=48)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('retry_delay_minutes', models.PositiveIntegerField(default=90)),
                ('retry_on_statuses', models.JSONField(default=list)),
                ('retry_backoff_factor', models.FloatField(default=1.5)),
                ('max_attempts_per_day', models.PositiveSmallIntegerField(default=2)),
                ('amd_enabled', models.BooleanField(default=True)),
                ('amd_mode', models.CharField(default='DetectMessageEnd', max_length=20)),
                ('amd_async', models.BooleanField(default=True)),
                ('amd_timeout_seconds', models.PositiveSmallIntegerField(default=30)),
                ('voicemail_node', models.CharField(blank=True, max_length=64)),
                ('hangup_on_machine', models.BooleanField(default=False)),
                ('record_calls', models.BooleanField(default=False)),
                ('recording_disclosure_node', models.CharField(blank=True, max_length=64)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('pause_reason', models.CharField(blank=True, max_length=160)),
                ('queue_built_at', models.DateTimeField(blank=True, null=True)),
                ('caller_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='campaigns.callerid')),
                ('contact_lists', models.ManyToManyField(related_name='campaigns', to='contacts.contactlist')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('flow_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='ivr.ivrflowversion')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unfiltered', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CampaignContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('dialing', 'Dialing'), ('done', 'Done'), ('failed', 'Failed'), ('suppressed', 'Suppressed'), ('exhausted', 'Attempts exhausted')], db_index=True, default='pending', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('next_attempt_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('final_disposition', models.CharField(blank=True, max_length=20)),
                ('priority', models.SmallIntegerField(default=0)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue', to='campaigns.campaign')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_entries', to='contacts.contact')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unfiltered', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CampaignStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_contacts', models.PositiveIntegerField(default=0)),
                ('dialed', models.PositiveIntegerField(default=0)),
                ('answered', models.PositiveIntegerField(default=0)),
                ('human', models.PositiveIntegerField(default=0)),
                ('machine', models.PositiveIntegerField(default=0)),
                ('no_answer', models.PositiveIntegerField(default=0)),
                ('busy', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('transferred', models.PositiveIntegerField(default=0)),
                ('opted_out', models.PositiveIntegerField(default=0)),
                ('suppressed', models.PositiveIntegerField(default=0)),
                ('confirmed', models.PositiveIntegerField(default=0)),
                ('voicemail', models.PositiveIntegerField(default=0)),
                ('dtmf_breakdown', models.JSONField(default=dict)),
                ('total_duration_seconds', models.BigIntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=5, default=0, max_digits=12)),
                ('last_flushed_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='campaigns.campaign')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unfiltered', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='callerid',
            index=models.Index(fields=['organization', 'is_active'], name='campaigns_c_organiz_5648ee_idx'),
        ),
        migrations.AddIndex(
            model_name='callerid',
            index=models.Index(fields=['provider', 'is_active'], name='campaigns_c_provide_784fbc_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['organization', 'status', '-created_at'], name='campaigns_c_organiz_644ec8_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(condition=models.Q(('status', 'running')), fields=['status'], name='idx_campaign_running'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(condition=models.Q(('status', 'scheduled')), fields=['scheduled_start'], name='idx_campaign_scheduled'),
        ),
        migrations.AddIndex(
            model_name='campaigncontact',
            index=models.Index(condition=models.Q(('state', 'pending')), fields=['campaign', 'priority', 'next_attempt_at'], name='idx_queue_claimable'),
        ),
        migrations.AddIndex(
            model_name='campaigncontact',
            index=models.Index(condition=models.Q(('state', 'dialing')), fields=['campaign', 'claimed_at'], name='idx_queue_stuck'),
        ),
        migrations.AddConstraint(
            model_name='campaigncontact',
            constraint=models.UniqueConstraint(fields=('campaign', 'contact'), name='uniq_campaign_contact'),
        ),
        migrations.AddIndex(
            model_name='campaignstats',
            index=models.Index(fields=['organization', '-updated_at'], name='campaigns_c_organiz_dbb389_idx'),
        ),
    ]
