# Generated by Django 5.2.4 on 2026-08-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='dial_batch_size',
            field=models.PositiveIntegerField(default=5, help_text='Calls released per interval, in pulse and ramp modes.'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='dial_interval_seconds',
            field=models.PositiveIntegerField(default=30, help_text='Seconds between batches, in pulse and ramp modes.'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='dial_mode',
            field=models.CharField(choices=[('fixed', 'Fixed — fill to the ceiling as fast as pacing allows'), ('pulse', 'Pulse — a fixed batch on a fixed beat'), ('ramp', 'Ramp — a batch per interval, released at random moments')], default='fixed', max_length=8),
        ),
    ]
