# Generated by Django 5.2.4 on 2026-08-12 13:10

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_auditlogentry_organization'),
        ('campaigns', '0002_campaign_dial_batch_size_and_more'),
        ('telephony', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('low_balance_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'unfiltered',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unfiltered', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CLIPool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('rotation', models.CharField(choices=[('random', 'Random — a number at random each call'), ('sequential', 'In order — cycle through the numbers'), ('least_used', 'Spread — the number used least today')], default='least_used', max_length=12)),
                ('members', models.ManyToManyField(blank=True, related_name='pools', to='campaigns.callerid')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'name'], name='campaigns_c_organiz_8fb16b_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unfiltered', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('prefix', models.CharField(help_text='e.g. +2547 or +1', max_length=12)),
                ('per_minute', models.DecimalField(decimal_places=4, max_digits=10)),
                ('connect_fee', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('increment_seconds', models.PositiveIntegerField(default=60)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            options={
                'ordering': ['-prefix'],
                'indexes': [models.Index(fields=['organization', 'prefix'], name='campaigns_t_organiz_dd39a0_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unfiltered', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='WalletEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('topup', 'Top-up'), ('charge', 'Call charge'), ('adjustment', 'Manual adjustment')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_entries', to='telephony.calllog')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='campaigns.wallet')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', '-created_at'], name='campaigns_w_organiz_d1573b_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unfiltered', django.db.models.manager.Manager()),
            ],
        ),
    ]
