# Generated by Django 5.2.4 on 2026-08-12 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_clipool_created_by'),
        ('ivr', '0003_audiopool_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='audio_pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ivr.audiopool'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='cli_pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='campaigns.clipool'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_number',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
