# Generated by Django 5.2.4 on 2026-08-03 13:26

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('campaigns', '0001_initial'),
        ('contacts', '0001_initial'),
        ('ivr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('provider_call_sid', models.CharField(db_index=True, max_length=64)),
                ('event_type', models.CharField(max_length=32)),
                ('sequence_number', models.IntegerField(blank=True, null=True)),
                ('payload', models.JSONField()),
                ('signature_valid', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'telephony_callevent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=16)),
                ('provider_call_sid', models.CharField(max_length=64, unique=True)),
                ('parent_call_sid', models.CharField(blank=True, max_length=64)),
                ('from_number', models.CharField(max_length=16)),
                ('to_number', models.CharField(max_length=16)),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('initiated', 'Initiated'), ('ringing', 'Ringing'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('busy', 'Busy'), ('no_answer', 'No answer'), ('failed', 'Failed'), ('canceled', 'Canceled')], db_index=True, default='queued', max_length=16)),
                ('answered_by', models.CharField(blank=True, choices=[('human', 'Human'), ('machine_start', 'Machine (greeting start)'), ('machine_end_beep', 'Machine (beep detected)'), ('machine_end_silence', 'Machine (silence)'), ('machine_end_other', 'Machine (other)'), ('fax', 'Fax'), ('unknown', 'Unknown')], max_length=20)),
                ('disposition', models.CharField(blank=True, choices=[('confirmed', 'Confirmed (DTMF)'), ('transferred', 'Transferred to agent'), ('opted_out', 'Opted out'), ('voicemail', 'Voicemail left'), ('abandoned', 'Abandoned by caller'), ('no_input', 'No DTMF input'), ('unreachable', 'Unreachable'), ('suppressed', 'Suppressed before dial')], max_length=20)),
                ('sip_response_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('initiated_at', models.DateTimeField(blank=True, null=True)),
                ('ringing_at', models.DateTimeField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('billable_seconds', models.PositiveIntegerField(default=0)),
                ('ring_seconds', models.PositiveSmallIntegerField(default=0)),
                ('amd_latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('node_path', models.JSONField(blank=True, default=list)),
                ('terminal_node', models.CharField(blank=True, max_length=64)),
                ('transferred_to', models.CharField(blank=True, max_length=64)),
                ('transfer_duration_seconds', models.PositiveIntegerField(default=0)),
                ('recording_url', models.CharField(blank=True, max_length=512)),
                ('recording_key', models.CharField(blank=True, max_length=512)),
                ('recording_duration', models.PositiveIntegerField(default=0)),
                ('recording_purged_at', models.DateTimeField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('cost_currency', models.CharField(default='USD', max_length=3)),
                ('cost_reconciled', models.BooleanField(default=False)),
                ('stir_attestation', models.CharField(blank=True, max_length=1)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='campaigns.campaign')),
                ('consent_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contacts.consentrecord')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='contacts.contact')),
                ('flow_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calls', to='ivr.ivrflowversion')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unfiltered', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DTMFResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node_id', models.CharField(max_length=64)),
                ('digits', models.CharField(max_length=32)),
                ('attempt', models.PositiveSmallIntegerField(default=1)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dtmf', to='telephony.calllog')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unfiltered', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['campaign', '-created_at'], name='telephony_c_campaig_998e41_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['campaign', 'status'], name='telephony_c_campaig_2e52ba_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['organization', 'to_number', '-created_at'], name='telephony_c_organiz_2fe310_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(condition=models.Q(('status__in', ['queued', 'initiated', 'ringing', 'in_progress'])), fields=['campaign'], name='idx_calls_live'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(condition=models.Q(('cost_reconciled', False)), fields=['cost_reconciled', '-created_at'], name='idx_calls_unreconciled'),
        ),
        migrations.AddIndex(
            model_name='dtmfresponse',
            index=models.Index(fields=['call', 'node_id'], name='telephony_d_call_id_52122f_idx'),
        ),
        migrations.AddIndex(
            model_name='dtmfresponse',
            index=models.Index(fields=['organization', '-created_at'], name='telephony_d_organiz_3d618f_idx'),
        ),
    ]
