# Generated by Django 5.2.4 on 2026-08-03 13:26

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('source_filename', models.CharField(blank=True, max_length=255)),
                ('source_key', models.CharField(blank=True, max_length=512)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('rejected_rows', models.PositiveIntegerField(default=0)),
                ('duplicate_rows', models.PositiveIntegerField(default=0)),
                ('suppressed_rows', models.PositiveIntegerField(default=0)),
                ('ingest_report', models.JSONField(blank=True, default=dict)),
                ('ingest_status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('ingest_started_at', models.DateTimeField(blank=True, null=True)),
                ('ingest_finished_at', models.DateTimeField(blank=True, null=True)),
                ('rejects_key', models.CharField(blank=True, max_length=512)),
                ('default_region', models.CharField(default='US', max_length=2)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unfiltered', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_e164', models.CharField(db_index=True, max_length=16)),
                ('phone_hash', models.CharField(db_index=True, max_length=64)),
                ('country_code', models.CharField(blank=True, max_length=4)),
                ('line_type', models.CharField(blank=True, max_length=16)),
                ('carrier_name', models.CharField(blank=True, max_length=80)),
                ('lookup_checked_at', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=80)),
                ('last_name', models.CharField(blank=True, max_length=80)),
                ('variables', models.JSONField(blank=True, default=dict)),
                ('timezone', models.CharField(default='UTC', max_length=48)),
                ('is_suppressed', models.BooleanField(default=False)),
                ('suppression_reason', models.CharField(blank=True, choices=[('internal_dnc', 'Internal DNC'), ('ivr_opt_out', 'Opted out via IVR'), ('federal_dnc', 'Federal DNC registry'), ('state_dnc', 'State DNC registry'), ('litigator', 'Known litigator / trap line'), ('carrier_invalid', 'Invalid or unassigned number'), ('wireless_block', 'Wireless, no consent on file'), ('complaint', 'Complaint received'), ('erasure_request', 'GDPR/CCPA erasure request'), ('no_consent', 'No consent record on file'), ('out_of_window', 'Outside permitted calling window'), ('attempt_cap', 'Daily attempt cap reached')], max_length=24)),
                ('suppressed_at', models.DateTimeField(blank=True, null=True)),
                ('last_called_at', models.DateTimeField(blank=True, null=True)),
                ('total_attempts', models.PositiveSmallIntegerField(default=0)),
                ('erased_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
                ('contact_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='contacts.contactlist')),
            ],
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unfiltered', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_e164', models.CharField(db_index=True, max_length=16)),
                ('phone_hash', models.CharField(db_index=True, max_length=64)),
                ('consent_type', models.CharField(choices=[('express_written', 'Prior express written consent'), ('express_oral', 'Prior express consent (oral)'), ('ebr', 'Established business relationship'), ('transactional', 'Transactional / informational')], max_length=32)),
                ('scope', models.CharField(choices=[('marketing', 'Marketing'), ('informational', 'Informational')], max_length=32)),
                ('source', models.CharField(max_length=64)),
                ('source_url', models.URLField(blank=True)),
                ('disclosure_text', models.TextField(blank=True)),
                ('captured_at', models.DateTimeField()),
                ('captured_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('captured_user_agent', models.TextField(blank=True)),
                ('evidence_ref', models.CharField(blank=True, max_length=255)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_channel', models.CharField(blank=True, max_length=32)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'phone_e164', '-captured_at'], name='contacts_co_organiz_caec06_idx'), models.Index(condition=models.Q(('revoked_at__isnull', True)), fields=['organization', 'phone_e164'], name='idx_consent_active'), models.Index(condition=models.Q(('revoked_at__isnull', True)), fields=['organization', 'phone_hash', 'scope'], name='idx_consent_hash_active')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unfiltered', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='contactlist',
            index=models.Index(fields=['organization', '-created_at'], name='contacts_co_organiz_f78cb0_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['organization', 'phone_hash'], name='contacts_co_organiz_a098d0_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(condition=models.Q(('is_suppressed', False)), fields=['contact_list', 'id'], name='idx_contact_dialable'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=django.contrib.postgres.indexes.GinIndex(fields=['variables'], name='idx_contact_vars_gin'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('contact_list', 'phone_e164'), name='uniq_contact_per_list'),
        ),
    ]
