# Generated by Django 5.2.4 on 2026-08-03 13:26

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IVRFlow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unfiltered', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='IVRFlowVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('definition', models.JSONField()),
                ('entry_node', models.CharField(max_length=64)),
                ('checksum', models.CharField(max_length=64)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('rendered_prompts', models.JSONField(blank=True, default=dict)),
                ('prompts_rendered_at', models.DateTimeField(blank=True, null=True)),
                ('validation_report', models.JSONField(blank=True, default=dict)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='ivr.ivrflow')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unfiltered', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TransferEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('pstn', 'PSTN number'), ('sip', 'SIP URI')], default='pstn', max_length=8)),
                ('destination', models.CharField(max_length=255)),
                ('caller_id_override', models.CharField(blank=True, max_length=16)),
                ('timeout_seconds', models.PositiveSmallIntegerField(default=30)),
                ('max_concurrent', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unfiltered', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AudioAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('storage_key', models.CharField(max_length=512)),
                ('mime_type', models.CharField(max_length=48)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('sample_rate', models.PositiveIntegerField(default=8000)),
                ('source', models.CharField(default='upload', max_length=24)),
                ('source_text', models.TextField(blank=True)),
                ('voice_id', models.CharField(blank=True, max_length=64)),
                ('render_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', '-created_at'], name='ivr_audioas_organiz_0e7cfe_idx'), models.Index(fields=['organization', 'render_key'], name='ivr_audioas_organiz_aab967_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unfiltered', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='ivrflow',
            index=models.Index(fields=['organization', '-created_at'], name='ivr_ivrflow_organiz_d5c2ae_idx'),
        ),
        migrations.AddConstraint(
            model_name='ivrflow',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uniq_flow_name_per_org'),
        ),
        migrations.AddIndex(
            model_name='ivrflowversion',
            index=models.Index(fields=['flow', '-version'], name='ivr_ivrflow_flow_id_3d92ea_idx'),
        ),
        migrations.AddConstraint(
            model_name='ivrflowversion',
            constraint=models.UniqueConstraint(fields=('flow', 'version'), name='uniq_flow_version'),
        ),
        migrations.AddIndex(
            model_name='transferendpoint',
            index=models.Index(fields=['organization', 'is_active'], name='ivr_transfe_organiz_c1fef2_idx'),
        ),
        migrations.AddConstraint(
            model_name='transferendpoint',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uniq_transfer_endpoint_name'),
        ),
    ]
