# Generated by Django 5.2.4 on 2026-08-12 13:10

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_auditlogentry_organization'),
        ('ivr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioPool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('rotation', models.CharField(choices=[('random', 'Random — a member at random each call'), ('sequential', 'In order — cycle through the members')], default='random', max_length=12)),
                ('members', models.ManyToManyField(blank=True, related_name='pools', to='ivr.audioasset')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'name'], name='ivr_audiopo_organiz_b424bc_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unfiltered', django.db.models.manager.Manager()),
            ],
        ),
    ]
